# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-15 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='crated_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='article',
            name='keyset',
            field=models.TextField(default=''),
        ),
    ]
