# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-05 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='catalog',
            field=models.CharField(choices=[('tech', '技术'), ('travel', '旅行'), ('literature', '文学'), ('health', '医疗健康')], max_length=32, verbose_name='目录'),
        ),
    ]
