# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-15 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20160905_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='catalog',
            field=models.CharField(choices=[('tech', '技术'), ('blog', '博客'), ('travel', '旅行'), ('literature', '文学'), ('health', '医疗健康')], max_length=32, verbose_name='目录'),
        ),
        migrations.AlterField(
            model_name='project',
            name='process_type',
            field=models.IntegerField(choices=[(1, 'CSS选择器'), (2, 'CSS'), (3, 'JSON'), (5, 'AUTO_MATCH')], default=1, verbose_name='处理类型'),
        ),
    ]
